### ISSUE TITLE
NPE@inflating

### ISSUE THREAD

**Issue by D3vel0pper** [D3vel0pper/Lifecyclestudy#2]
[detail]
FATAL EXCEPTION: main
    java.lang.NullPointerException
            at t4ka.com.lifecyclestudy.MainActivity.inflatingLayout(MainActivity.java:194)
            at t4ka.com.lifecyclestudy.MainActivity.onClick(MainActivity.java:177)

**Comment by D3vel0pper** [comment]
This needs to resolve layout parameter on the inflated layout's root element.
May be need the root ViewGroupe??

**Comment by D3vel0pper** [comment]
Added root ViewGroupe, But still NPE occur.

**Comment by D3vel0pper** [comment]
check out ur showDatas and member valuables of SQLProcesser.

**Comment by D3vel0pper** [comment]
String data is correct. But when assign to tv.text, it return null.

**Comment by D3vel0pper** [comment]
It may not be able to resolve the component of findViewById.
tell which view do u mean.
